version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: triangulation_app
    ports:
      - "8081:80"
    volumes:
      - ./src/public:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
